### ISSUE TITLE
Proto-Staking: Fix `stakeBalance`

### ISSUE THREAD

**Issue by pmolina** [exactly/app#1168]

**Comment by jgalat** [comment]
The issue here is that we are not using a minimum supply for `stakeBalance`.

If the user sends the value returned by `previewETH` it may happen that the new updated value used by the contract decreased by a tiny amount, which results in the contract trying to swap the delta into EXA. This reverts with `K()`.

There is no easy way around this that will prevent the user from seeing the `You need to supply more than X` message when typing the value displayed in the preview. Adding minimum supply for this will also result in swaps always being performed with each interaction.
